[package]
name = "iron-r2d2-mysql-middleware"
version = "0.1.0"
authors = ["Pocket7878 <poketo7878@gmail.com>"]

[dependencies]
iron = "0.4.0"
r2d2 = "0.7.0"
r2d2_mysql = { git = "https://github.com/outersky/r2d2-mysql.git" }
